/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : Z:\home\rafagars\gbdk\GBTD\BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BackgroundMap_h_INCLUDE
#define __BackgroundMap_h_INCLUDE

#define BackgroundMapWidth 32
#define BackgroundMapHeight 18
#define BackgroundMapBank 0

extern const unsigned char BackgroundMap[];

#endif

/* End of BACKGROUNDMAP.H */
