/*

 BACKGROUNDMAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : Z:\home\rafagars\gbdk\GBTD\BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BackgroundMap3_h_INCLUDE
#define __BackgroundMap3_h_INCLUDE

#define BackgroundMap3Width 32
#define BackgroundMap3Height 18
#define BackgroundMap3Bank 0

extern const unsigned char BackgroundMap3[];

#endif

/* End of BACKGROUNDMAP3.H */
