/*

 BACKGROUNDMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : Z:\home\rafagars\gbdk\GBTD\BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BackgroundMap2_h_INCLUDE
#define __BackgroundMap2_h_INCLUDE

#define BackgroundMap2Width 32
#define BackgroundMap2Height 18
#define BackgroundMap2Bank 0

extern const unsigned char BackgroundMap2[];

#endif

/* End of BACKGROUNDMAP2.H */
