/*

 PLANE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Plane[] =
{
  0x00,0x00,0x00,0x20,0x00,0x30,0x00,0x3F,
  0x00,0x3F,0x00,0x61,0x00,0x03,0x00,0x06,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xF0,
  0x00,0xF8,0x00,0x80,0x00,0x00,0x00,0x00
};

/* End of PLANE.C */
